// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Schedule struct {
	ID            string
	Handler       string
	Payload       []byte
	Cron          string
	Timezone      string
	Status        string
	TimeoutMs     int64
	MisfirePolicy string
	NextRunAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Task struct {
	ID         string
	ScheduleID pgtype.Text
	RunType    string
	Handler    string
	Payload    []byte
	RunAt      pgtype.Timestamptz
	Status     string
	TimeoutMs  int64
	Attempts   int32
	Output     pgtype.Text
	Error      pgtype.Text
	CreatedAt  pgtype.Timestamptz
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}
