// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package postgres

import (
	"context"
)

const getAllTasks = `-- name: GetAllTasks :many
SELECT id, schedule_id, run_type, handler, payload, run_at, status, timeout_ms, attempts, output, error, created_at, started_at, finished_at FROM tasks
`

func (q *Queries) GetAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.RunType,
			&i.Handler,
			&i.Payload,
			&i.RunAt,
			&i.Status,
			&i.TimeoutMs,
			&i.Attempts,
			&i.Output,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
